### ISSUE TITLE
[bug] IndexError: list index out of range

### ISSUE THREAD

**Issue by missuo** [njzjz/zhihubackup#22]
```
File ["/opt/homebrew/lib/python3.12/site-packages/zhihubackup/backup.py", line 64](coderunner:///opt/homebrew/lib/python3.12/site-packages/zhihubackup/backup.py#64:0!), in loop
    jdata = get_json(api, cookie)
            ^^^^^^^^^^^^^^^^^^^^^
  File ["/opt/homebrew/lib/python3.12/site-packages/zhihubackup/backup.py", line 36](coderunner:///opt/homebrew/lib/python3.12/site-packages/zhihubackup/backup.py#36:0!), in get_json
    d_c0 = cookie.split("d_c0=")[1].split(";")[0]
           ~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

**Comment by njzjz** [comment]
The reason is that Zhihu requests verification as shown below. 

```json
{"error": {"need_login": true, "redirect": "https://www.zhihu.com/account/unhuman?type=S6E3V1&need_login=true", "code": 40352, "message": "系统监测到您的网络环境存在异常，为保证您的正常访问，请点击下方验证按钮进行验证。在您验证完成前，该提示将多次出现。"}}
```

I don't think I can bypass it, so I allow users to set cookies through the environment variable `ZHIHU_COOKIES`.

**Comment by missuo** [comment]
I'm not sure that the logined status cookie prevents authentication from occurring. With **AS701 Verizon Fios** access, you have to complete a verification on almost every page.

I noticed that this verification is just some graphics in the wrong direction and it should be possible to finish it.

**Comment by njzjz** [comment]
> I'm not sure that the logined status cookie prevents authentication from occurring.

At least, the unit tests have passed (it failed before), so I think it should work.

**Comment by missuo** [comment]
OK. I'll have a try.

Could you release a new version? It has not been updated on [pypi](https://pypi.org/project/zhihubackup/) yet.

**Comment by missuo** [comment]
It works. Thank you very much.
